export * from './IConfiguration'
export * from './IEventType'
export * from './IGbifferenceData'
export * from './IOccurrences'
export * from './IRemark'
export * from './IRequestOptions'
export * from './ITable'